[package]
name = "ichnos-stats"
description = "Log statistics and filtering."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ichnos-core = { workspace = true }
ichnos-model = { workspace = true }
indexmap = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
arrow = { workspace = true, features = ["csv"] }
ichnos-golden = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
