[package]
name = "ichnos-stream"
description = "Streaming process mining."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
arrow = { workspace = true }
csv = { workspace = true }
flate2 = { workspace = true }
ichnos-conformance = { workspace = true }
ichnos-core = { workspace = true }
ichnos-discovery = { workspace = true }
ichnos-io = { workspace = true }
ichnos-model = { workspace = true }
quick-xml = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ichnos-golden = { workspace = true }
serde_json = { workspace = true, features = ["float_roundtrip"] }
sha2 = { workspace = true }
