//! Typed form of the `log` area: basic statistics of an event log.
//!
//! Generated by `tools/golden/cases/log.py`. Load one with
//! `golden("log", case).expected_as::<LogSummary>()`.

use std::collections::BTreeMap;

use serde::Deserialize;

/// Basic statistics of one event log, as pm4py computes them.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LogSummary {
    /// Number of distinct case ids.
    pub n_cases: u64,
    /// Number of events.
    pub n_events: u64,
    /// Activity to number of events with that activity.
    pub activities: BTreeMap<String, u64>,
    /// Activity to number of cases that start with it.
    pub start_activities: BTreeMap<String, u64>,
    /// Activity to number of cases that end with it.
    pub end_activities: BTreeMap<String, u64>,
    /// Variants with their case counts, sorted by activity sequence.
    pub variants: Vec<VariantCount>,
    /// Directly-follows pairs with their counts, sorted by (source, target).
    pub dfg: Vec<DfgEdge>,
}

/// One variant: an activity sequence and the number of cases that follow it.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VariantCount {
    /// The activity sequence.
    pub activities: Vec<String>,
    /// Number of cases.
    pub count: u64,
}

/// One directly-follows edge with its count.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DfgEdge {
    /// The earlier activity.
    pub source: String,
    /// The activity that directly follows it.
    pub target: String,
    /// Number of times `target` directly follows `source`.
    pub count: u64,
}

impl LogSummary {
    /// Variants as a map from activity sequence to case count.
    pub fn variant_counts(&self) -> BTreeMap<Vec<String>, u64> {
        self.variants
            .iter()
            .map(|v| (v.activities.clone(), v.count))
            .collect()
    }

    /// The DFG as a map from `(source, target)` to count.
    pub fn dfg_counts(&self) -> BTreeMap<(String, String), u64> {
        self.dfg
            .iter()
            .map(|e| ((e.source.clone(), e.target.clone()), e.count))
            .collect()
    }
}
