"""Writes the table of characters that Python's ``repr`` escapes.

``repr`` of a string escapes every character for which ``str.isprintable()``
is false. This script lists those code points as ranges for
``crates/ichnos-core/src/python/nonprintable.rs``. Run it with the Python
that the goldens use, so the Unicode version matches::

    python tools/python_nonprintable.py > crates/ichnos-core/src/python/nonprintable.rs
"""

import sys
import unicodedata


def ranges():
    out, start = [], None
    for c in range(sys.maxunicode + 1):
        hidden = not chr(c).isprintable()
        if hidden and start is None:
            start = c
        elif not hidden and start is not None:
            out.append((start, c - 1))
            start = None
    if start is not None:
        out.append((start, sys.maxunicode))
    return out


def main():
    rows = ranges()
    print(
        "//! Code points that Python's `str.isprintable` rejects, as inclusive\n"
        f"//! ranges (Python {sys.version_info.major}.{sys.version_info.minor}, "
        f"Unicode {unicodedata.unidata_version}).\n"
        "//!\n"
        "//! Generated by `tools/python_nonprintable.py`; do not edit.\n"
    )
    print("#[rustfmt::skip]")
    print(f"pub(super) const RANGES: [(u32, u32); {len(rows)}] = [")
    for i in range(0, len(rows), 6):
        line = " ".join(f"(0x{a:x}, 0x{b:x})," for a, b in rows[i : i + 6])
        print(f"    {line}")
    print("];")


if __name__ == "__main__":
    main()
